import { StyleSheet } from "react-native";
import { colors } from "../../theme/colors";
import { COLORS, GUTTER_W } from "./calendarConstants";

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: COLORS.deep,
  },
  root: {
    flex: 1,
    position: "relative",
    backgroundColor: COLORS.deep,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.deep,
  },
  dateStrip: {
    backgroundColor: COLORS.deep,
    maxHeight: 60,
    flexGrow: 0,
    flexShrink: 0,
  },
  dateStripContent: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 4,
    paddingHorizontal: 12,
    gap: 8,
  },
  dateChip: {
    flexShrink: 0,
    minWidth: 44,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 10,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "transparent",
  },
  dateChipSelected: {
    backgroundColor: "rgba(245,243,239,0.16)",
    borderColor: "rgba(245,243,239,0.30)",
  },
  dateChipDim: {
    opacity: 0.45,
  },
  dateChipToday: {
    borderColor: "rgba(0,214,143,0.20)",
    borderWidth: 1,
  },
  dateChipDow: {
    fontSize: 10,
    color: COLORS.slate,
    fontWeight: "500",
    fontFamily: "Satoshi-Medium",
    letterSpacing: 0.5,
    textTransform: "uppercase" as const,
  },
  dateChipDowSelected: {
    color: COLORS.steel,
    fontWeight: "700",
    fontFamily: "Satoshi-Bold",
  },
  dateChipDowToday: {
    color: COLORS.slate,
  },
  dateChipNum: {
    fontSize: 15,
    fontWeight: "600",
    fontFamily: "Satoshi-Bold",
    marginTop: 2,
  },
  dateChipNumSelected: {
    color: COLORS.steel,
    fontWeight: "700",
    fontFamily: "Satoshi-Bold",
  },
  dateChipNumToday: {
    color: COLORS.steel,
  },
  dateChipNumIdle: {
    color: colors.textPrimary,
  },
  workingDotRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    marginTop: 2,
  },
  workingDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.nova500,
  },
  dateChipCount: {
    fontSize: 9,
    fontWeight: "600",
    fontFamily: "Satoshi-Bold",
    color: "rgba(245,243,239,0.40)",
    fontVariant: ["tabular-nums"],
  },
  gridScroll: {
    flex: 1,
    backgroundColor: COLORS.warmBg,
  },
  gridScrollContent: {
    paddingBottom: 120,
  },
  gridRow: {
    flexDirection: "row",
    alignSelf: "stretch",
    backgroundColor: COLORS.warmBg,
  },
  gutterCol: {
    width: GUTTER_W,
    backgroundColor: COLORS.deep,
    zIndex: 2,
  },
  gutterInner: {
    position: "relative",
  },
  gutterLabel: {
    position: "absolute",
    right: 8,
    fontSize: 11,
    fontWeight: "500",
    fontFamily: "Satoshi-Medium",
    color: "rgba(245,243,239,0.55)",
    letterSpacing: 0.3,
  },
  nowBadgeWrap: {
    position: "absolute",
    left: 2,
    zIndex: 3,
  },
  nowBadge: {
    fontSize: 10,
    fontWeight: "600",
    fontFamily: "Satoshi-Bold",
    color: COLORS.deep,
    backgroundColor: COLORS.now,
    borderRadius: 4,
    paddingVertical: 2,
    paddingHorizontal: 6,
    overflow: "hidden",
  },
  gridDivider: {
    width: 0,
  },
  calendarCol: {
    flex: 1,
  },
  paperColumn: {
    position: "relative",
    backgroundColor: COLORS.warmBg,
  },
  unavailableShade: {
    position: "absolute",
    left: 0,
    right: 0,
    backgroundColor: colors.calendarUnavailable,
    zIndex: 0,
  },
  gridHLine: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 1,
    zIndex: 1,
  },
  gridHLineFull: {
    backgroundColor: "rgba(0,0,0,0.08)",
  },
  gridHLineHalf: {
    backgroundColor: "rgba(0,0,0,0.04)",
  },
  nowLine: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 1.5,
    backgroundColor: COLORS.now,
    zIndex: 10,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: COLORS.now,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 6,
  },
  nowDot: {
    position: "absolute",
    left: -4,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.now,
    marginTop: -3,
    shadowColor: COLORS.now,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
    elevation: 6,
  },
  apptCard: {
    position: "absolute",
    backgroundColor: colors.calendarCardBg,
    borderRadius: 6,
    paddingTop: 5,
    paddingBottom: 6,
    paddingHorizontal: 10,
    zIndex: 5,
    shadowColor: "rgba(0,0,0,0.18)",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 1,
    shadowRadius: 12,
    elevation: 4,
    overflow: "hidden",
    borderTopWidth: 1,
    borderTopColor: "rgba(245,243,239,0.09)",
  },
  apptCardCompleted: {
    backgroundColor: colors.obsidian800,
    borderWidth: 1,
    borderColor: "rgba(0,214,143,0.25)",
    borderRadius: 6,
    shadowColor: COLORS.novaGold,
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 10,
  },
  apptCardDragging: {
    opacity: 0.9,
    shadowColor: "#00D68F",
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 16,
    elevation: 12,
    zIndex: 50,
    transform: [{ scale: 1.03 }],
  },
  apptCardNoshow: {
    backgroundColor: colors.calendarCardBg,
    borderRadius: 6,
    borderLeftWidth: 3,
    borderLeftColor: COLORS.red,
  },
  apptCardLifting: {
    transform: [{ scale: 1.025 }],
    shadowColor: "#00D68F",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
    elevation: 8,
    zIndex: 40,
  },
  overlapDot: {
    position: "absolute",
    top: 6,
    right: 52,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.amber,
    zIndex: 6,
  },
  apptTime: {
    fontSize: 11,
    fontWeight: "400",
    fontFamily: "Satoshi-Regular",
    color: colors.textSecondary,
    letterSpacing: 0.2,
  },
  apptClient: {
    fontSize: 14,
    fontWeight: "600",
    fontFamily: "Satoshi-Bold",
    color: colors.textPrimary,
    letterSpacing: -0.2,
    marginTop: 1,
    paddingRight: 36,
  },
  apptClientCompleted: {
    color: colors.nova400,
  },
  apptClientNoshow: {
    color: colors.textSecondary,
    textDecorationLine: "line-through",
    textDecorationColor: COLORS.red,
  },
  apptService: {
    fontSize: 11,
    fontWeight: "400",
    fontFamily: "Satoshi-Regular",
    color: "rgba(245,243,239,0.50)",
    marginTop: 1,
  },
  apptServiceInline: {
    fontSize: 11,
    fontWeight: "400",
    fontFamily: "Satoshi-Regular",
    color: "rgba(245,243,239,0.35)",
  },
  apptServiceCompleted: {
    color: colors.textSecondary,
  },
  apptTimeCompleted: {
    color: colors.textSecondary,
  },
  apptTimeNoshow: {
    color: colors.textSecondary,
  },
  apptPrice: {
    position: "absolute",
    top: 8,
    right: 10,
    fontSize: 14,
    fontWeight: "400",
    fontFamily: "DMSerifText-Regular",
    color: COLORS.novaGold,
  },
  noshowLabel: {
    position: "absolute",
    bottom: 8,
    right: 10,
    fontSize: 9,
    fontWeight: "600",
    fontFamily: "Satoshi-Bold",
    color: COLORS.red,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  blockCard: {
    position: "absolute",
    left: 4,
    right: 4,
    backgroundColor: colors.calendarBlockBg,
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
    zIndex: 4,
    justifyContent: "center",
    overflow: "hidden",
  },
  dragBand: {
    position: "absolute",
    left: 0,
    right: 0,
    backgroundColor: "rgba(0,214,143,0.10)",
    borderWidth: 1.5,
    borderColor: "rgba(0,214,143,0.40)",
    borderRadius: 6,
    zIndex: 20,
    justifyContent: "center",
    paddingHorizontal: 12,
    shadowColor: "#00D68F",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
  },
  dragLabel: {
    fontSize: 13,
    fontWeight: "600",
    fontFamily: "Satoshi-Bold",
    color: COLORS.novaGold,
  },
  slotMenuBand: {
    position: "absolute",
    left: 0,
    right: 0,
    backgroundColor: "rgba(0,214,143,0.10)",
    borderWidth: 1,
    borderColor: "rgba(0,214,143,0.30)",
    borderRadius: 6,
    zIndex: 20,
  },
  slotMenu: {
    position: "absolute",
    left: 16,
    right: 16,
    zIndex: 25,
    backgroundColor: colors.obsidian700,
    borderRadius: 14,
    padding: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 10,
  },
  slotMenuTime: {
    fontSize: 14,
    fontWeight: "600",
    fontFamily: "Satoshi-Bold",
    color: colors.textPrimary,
    textAlign: "center",
    marginBottom: 12,
  },
  slotMenuActions: {
    flexDirection: "row",
    borderRadius: 10,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(245,243,239,0.08)",
  },
  slotMenuBtn: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
    backgroundColor: "rgba(245,243,239,0.04)",
  },
  slotMenuDivider: {
    width: 1,
    backgroundColor: "rgba(245,243,239,0.08)",
  },
  slotMenuBtnTextGreen: {
    fontSize: 15,
    fontWeight: "600",
    fontFamily: "Satoshi-Bold",
    color: COLORS.novaGold,
  },
  slotMenuBtnText: {
    fontSize: 15,
    fontWeight: "600",
    fontFamily: "Satoshi-Bold",
    color: colors.textPrimary,
  },
  slotMenuCancel: {
    fontSize: 13,
    fontWeight: "500",
    fontFamily: "Satoshi-Medium",
    color: colors.textTertiary,
    textAlign: "center",
    marginTop: 10,
  },
  fabContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    top: 0,
    zIndex: 99,
    justifyContent: "flex-end",
    alignItems: "flex-end",
    paddingBottom: 28,
    paddingRight: 20,
  },
  fab: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.nova500,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.nova500,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 14,
    elevation: 8,
  },
  superstarBadge: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(19,21,24,0.9)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
    borderWidth: 1.5,
    borderColor: "rgba(0,214,143,0.35)",
    shadowColor: "#00D68F",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
  },
  superstarStar: {
    fontSize: 22,
  },
  blockRepeatIcon: {
    position: "absolute",
    top: 8,
    right: 10,
  },
  blockTime: {
    fontSize: 11,
    fontWeight: "400",
    fontFamily: "Satoshi-Regular",
    color: colors.textTertiary,
    letterSpacing: 0.2,
  },
  blockReason: {
    fontSize: 13,
    fontWeight: "500",
    fontFamily: "Satoshi-Medium",
    color: colors.textPrimary,
    marginTop: 2,
    paddingRight: 28,
  },
  emptyState: {
    position: "absolute",
    left: 0,
    right: 0,
    alignItems: "center",
    zIndex: 0,
  },
  emptyStateName: {
    fontSize: 17,
    fontWeight: "500",
    fontFamily: "Satoshi-Medium",
    color: "rgba(0,0,0,0.30)",
  },
  emptyStateText: {
    fontSize: 13,
    fontWeight: "400",
    fontFamily: "Satoshi-Regular",
    color: "rgba(0,0,0,0.20)",
    marginTop: 6,
  },
  blockReasonInline: {
    fontSize: 12,
    fontWeight: "500",
    fontFamily: "Satoshi-Medium",
    color: colors.textPrimary,
    paddingRight: 28,
  },
});
